<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="3.0" xmlns:edmx="http://schemas.microsoft.com/ado/2009/11/edmx">
 <!-- EF Designer content (DO NOT EDIT MANUALLY BELOW HERE) -->
  <edmx:Designer xmlns="http://schemas.microsoft.com/ado/2009/11/edmx">
    <!-- Diagram content (shape and connector positions) -->
    <edmx:Diagrams>
      <Diagram DiagramId="bc401e0b18e7478eb4d78fa37db5de64" Name="Diagram1" >
        <EntityTypeShape EntityType="Model1.Books" Width="1.5" PointX="8" PointY="1.125" />
        <EntityTypeShape EntityType="Model1.Author" Width="1.5" PointX="1.75" PointY="1.125" />
        <EntityTypeShape EntityType="Model1.AuthorBooks" Width="1.5" PointX="4.625" PointY="0.875" />
        <AssociationConnector Association="Model1.Entity1Author" />
        <AssociationConnector Association="Model1.BooksEntity1" />
      </Diagram>
    </edmx:Diagrams>
  </edmx:Designer>
</edmx:Edmx>